name: RunTests

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    # Measurement Service
    - name: Restore dependencies for Measurement Service
      run: dotnet restore Measurements_Service

    - name: Build Measurement Service
      run: dotnet build --configuration Release Measurements_Service

    - name: Test Measurement Service
      run: dotnet test --no-restore --verbosity normal Measurements_Service
    
    # Patient Service
    - name: Restore dependencies for Patient Service
      run: dotnet restore Patient-Service/API

    - name: Build Patient Service
      run: dotnet build --configuration Release Patient-Service/API

    - name: Test Patient Service
      run: dotnet test --no-restore --verbosity normal Patient-Service/API
