name: RustTest

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build project Measurement
      run: cargo build --verbose
      working-directory: measurement-service

    - name: Run tests Measurement
      run: cargo test
      working-directory: measurement-service

    - name: Build project Patient
      run: cargo build --verbose
      working-directory: patient-service

    - name: Run tests Patient
      run: cargo test
      working-directory: patient-service
