name: RunTests

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    # Measurement Service
    - name: Build and Test Measurement Service
      run: |
        cd Measurments_Service
        dotnet build
        dotnet test
    
    # Patient Service
    - name: Build and Test Patient Service
      run: |
        cd Patient-Service/API
        dotnet build
        dotnet test
