@Measurments_Service_HostAddress = https://localhost:7102

GET {{Measurments_Service_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Measurments_Service_HostAddress}}/Measurment/AddMeasurement/{SSN}

###
